### ISSUE TITLE
Implement std::str::FromStr for OpCode

### ISSUE THREAD

**Issue by Hasenn** [do-core/do-core1#3]
As of now, in my [assembler](https://github.com/Hasenn/do-core-asm) I need to redefine OpCode in order to derive that trait -- with strum's EnumString derive macro, which is a code duplication i can't really avoid. if the do-core crate did it, i could depend on it and not have to sync my assembler's instructions with do-core manually

**Comment by sameo** [comment]
Fixed with #4
